### ISSUE TITLE
Trust score drop due to forks

### ISSUE THREAD

**Issue by kousthubraja** [newrlfoundation/newrl#22]
Issue - The nodes from a fork can send blocks to the rest of the network causing the majority to drop the trust scores. 
    Once the fork is resolved, the trust score drop stays in state. Hence the nodes which are forked are no longer selected to mine.

Possible solutions
1. Ignore the blocks and receipts from different fork.
2. Don't send receipts and blocks to different fork.
3. Don't drop scores for blocks from different fork. 
4. Drop scores very minimally for forking. But this is a problem if fork is created by mistake.

Reasons for fork generation
1. Expected miner sending blocks with two different hash for same index on retry. This is fixed.
2. When consensus is obtained by two different set of receipt votes.
   When node 1 gets receipts [1, 2, 3, 4, 5, 6] and node 2 get receipts from [2, 3, 4, 5, 6, 7], they both accept the block and propagate.
   Need to investigate if this create a problem. Hopefully this should be fine as the receipts for consensus are not included in the block
   or affect trust scores.

Challenges
1. How to figure out a node is from different fork and not malicious

**Comment by swapnilpawar31415** [comment]
The trust score changes happen due to receipts processed in subsequent blocks. If we continue to store ignored blocks in temp until up to 100 blocks later (for example), the receipt for a block submitted from a fork to the network can be tallied with the block in temp to confirm that its previous block hash did not match the local node's previous block hash. This could indicate a fork instead of a malicious block. Instead, if the previous block hash matches but the block is invalid on account of its transactions, that is clearly a malicious block.

Also, committees voting on a block can ignore a block with non-matching previous hash instead of sending negative votes on it. They can process only blocks that have same previous hash as their own and then evaluate it for validity and vote yes or no based on the validity.

Same for committee receipts - ignore if they refer to blocks that do not match previous hash. (We may need to bring previous hash in the receipt data.)
